version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"

    - package-ecosystem: "npm"
      directory: "/test/jest/fixtures/app"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"

    - package-ecosystem: "cargo"
      directory: "/test/jest/fixtures/app/src-tauri"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only
      

    - package-ecosystem: "npm"
      directory: "/test/jest/fixtures/empty"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"
